/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Object;

import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dave van Rijn, Student 500714558, Klas IS202
 */
public class MeetingPanel extends javax.swing.JPanel {

    private boolean deletePressed = false;
    private boolean detailsPressed = false;
    private Meeting meeting;

    /**
     * Creates new form MeetingPanel
     */
    public MeetingPanel() {
        initComponents();
    }

    public MeetingPanel(Meeting meeting) {
        this();
        if (meeting != null) {
            this.meeting = meeting;
            SimpleDateFormat dateForm = new SimpleDateFormat("dd-MM-yy HH:mm");
            String start = dateForm.format(meeting.getStart());
            String end = dateForm.format(meeting.getEnd());

            lblTitle.setText(meeting.getTitle());
            lblTime.setText(start + " - " + end);
        } else {
            lblTitle.setText("Titel");
            lblTime.setText("Begin - Eindtijd");
            btnDelete.setVisible(false);
            btnDetails.setVisible(false);
            jSeparator1.setVisible(false);
        }
    }

    private void deleteMeeting() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        btnDetails = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTitle.setText("Test afspraak 1");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, 135, 20));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTime.setText("24-4-2016 14:03 - 25-4-2016 14:03");
        add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 16, -1, -1));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/exitIcon20x20.png"))); // NOI18N
        btnDelete.setToolTipText("Verwijderen");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeleteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDeleteMouseReleased(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 16, -1, -1));

        btnDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/lensIcon20x20.png"))); // NOI18N
        btnDetails.setToolTipText("Details");
        btnDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDetailsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDetailsMouseReleased(evt);
            }
        });
        add(btnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 16, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMousePressed
        if (evt.getButton() == MouseEvent.BUTTON1) {
            btnDelete.setIcon(new ImageIcon(getClass().getResource("/Resource/exitIcon20x20Clicked.png")));
            deletePressed = true;
        }
    }//GEN-LAST:event_btnDeleteMousePressed

    private void btnDeleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseReleased
        btnDelete.setIcon(new ImageIcon(getClass().getResource("/Resource/exitIcon20x20.png")));
        if (deletePressed) {
            deletePressed = false;
            int option = JOptionPane.showOptionDialog(null, "Weet je zeker dat je"
                    + " afspraak '" + meeting.getTitle() + "' wil verwijderen?",
                    "Bevestig", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                    null, new Object[]{"Ja", "Nee"}, "Nee");

            if (option == JOptionPane.YES_OPTION) {
                deleteMeeting();
            }
        }
    }//GEN-LAST:event_btnDeleteMouseReleased

    private void btnDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailsMousePressed
        if(evt.getButton() == MouseEvent.BUTTON1){
            btnDetails.setIcon(new ImageIcon(getClass().getResource("/Resource/lensIcon20x20Clicked.png")));
            detailsPressed = true;
        }
    }//GEN-LAST:event_btnDetailsMousePressed

    private void btnDetailsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailsMouseReleased
        btnDetails.setIcon(new ImageIcon(getClass().getResource("/Resource/lensIcon20x20.png")));
        if(detailsPressed){
            detailsPressed = false;
        }
    }//GEN-LAST:event_btnDetailsMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnDetails;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
