/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Exception.CharNotSupportedException;
import Main.Main;
import Object.User;
import Resource.FileUtil;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dave van Rijn, Student 500714558, Klas IS202
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    private void login(String username, String password) {
        List<User> users = (List<User>) FileUtil.get(FileUtil.USERS);
        if (users != null && !users.isEmpty()) {
            try {
                String encryptedPass = Main.encrypt(password);
                for (User u : users) {
                    if (u.getUsername().equals(username) && u.getPassword().equals(encryptedPass)) {
                        Main.setCurrentUser(u);
                        if (Main.getCurrentUser() != null) {
                            Main.setPanel(new Startpage());
                            return;
                        }
                    }
                }
                falseLogin("Combi");
            } catch (CharNotSupportedException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                falseLogin("Pass");
            }
        } else {
            falseLogin("Combi");
        }
    }

    private void falseLogin(String source) {
        switch (source) {
            case "Combi":

                break;
            case "Pass":

                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
