/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Keeper.View;

import Shared.Resource.FileUtil;
import Shared.Object.Meeting;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Dave van Rijn, Student 500714558, Klas IS202
 */
public class MeetingPanel extends javax.swing.JPanel {

    /**
     * Creates new form MeetingPanel
     */
    public MeetingPanel() {
        initComponents();
        setOpaque(false);
    }

    public MeetingPanel(Meeting meeting) {
        this();
        init(meeting);
    }

    public void setMeeting(Meeting meeting) {
        init(meeting);
    }

    public void setColor(Color color) {
        lblTime.setForeground(color);
        lblTitle.setForeground(color);
    }

    private void init(Meeting meeting) {
        if (meeting != null) {
            lblTime.setText(meeting.getMeetingTime());
            lblTitle.setText(meeting.getTitle());
            lblTitle.setPreferredSize(new Dimension(150, 25));

            MouseAdapter mouseAdap = new MouseAdapter() {
                @Override
                public void mouseReleased(MouseEvent e) {
                    FileUtil.add(FileUtil.SELECTED_MEETING, meeting);
                    Keeper.openAgenda();
                }
            };
            addMouseListener(mouseAdap);
            lblTime.addMouseListener(mouseAdap);
            lblTitle.addMouseListener(mouseAdap);
        } else {
            noMeeting();
        }
    }

    private void noMeeting() {
        lblTime.setText("Geen afspraken..");
        lblTitle.setVisible(false);
        MouseAdapter mouseAdap = new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                FileUtil.add(FileUtil.SELECTED_MEETING, null);
                Keeper.openAgenda();
            }
        };
        addMouseListener(mouseAdap);
        lblTime.addMouseListener(mouseAdap);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTime = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 102, 0));
        lblTitle.setText("Test meeting 1");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 47, 180, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 194, 10));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 102, 0));
        lblTime.setText("18:29 - 18:30");
        add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 180, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
