/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Agenda.View;

import Agenda.Object.MeetingPanel;
import Agenda.View.Agenda;
import Shared.Object.Meeting;
import Shared.Object.User;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Dave van Rijn, Student 500714558, Klas IS202
 */
public class Startpage extends javax.swing.JPanel {

    /**
     * Creates new form Startpage
     */
    public Startpage() {
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void initMyComponents() {
        setPreferredSize(new Dimension(944, 530));
        JPanel pnlMeetings = new JPanel();
        pnlMeetings.setLayout(new AbsoluteLayout());
        User current = Agenda.getCurrentUser();
        List<Meeting> todayMeetings = current.getAgenda().getTodayMeetings();
        int x = 0;
        int y = 0;
        int width = 520;
        int height = 48;
        int panelHeight = height * todayMeetings.size();

        pnlMeetings.add(new MeetingPanel(null), new AbsoluteConstraints(x, y, width, height));
        y += height;
        for (Meeting m : todayMeetings) {
            pnlMeetings.add(new MeetingPanel(m), new AbsoluteConstraints(x, y, width, height));
            y += height;
        }
        JScrollPane scrollPane = new JScrollPane(pnlMeetings);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.getVerticalScrollBar().setUnitIncrement(30);
        int scrollHeight = 530;
        int scrollX = getPreferredSize().width - width;

        add(scrollPane, new AbsoluteConstraints(scrollX, 0, width, scrollHeight));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
