/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Agenda;

import Exception.CharNotSupportedException;
import TimeKeeper.FileUtil;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dave van Rijn, Student 500714558, Klas IS202
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    private void login(String username, String password) {
        List<User> users = (List<User>) FileUtil.get(FileUtil.USERS);
        if (users != null && users.size() > 0) {
            try {
                String encryptedPass = Main.encrypt(password);
                for (User u : users) {
                    if (u.getPassword().equals(encryptedPass)) {
                        Main.setCurrentUser(u);
                        break;
                    }
                }
                if (Main.getCurrentUser() != null) {
                    Main.setPanel(new Startpage());
                } else {
                    falseLogin();
                }
            } catch (CharNotSupportedException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            falseLogin();
        }
    }

    private void falseLogin() {

    }

    private void register(String username, String password, String firstname,
            String infix, String lastname, String address, String addressExtra,
            String city, String country, int houseNumber, Date birthday) {
        try {
            List<User> users = (List<User>) FileUtil.get(FileUtil.USERS);
            if (users != null) {
                if (!users.isEmpty()) {
                    for (User u : users) {
                        if (u.getUsername().equals(username)) {
                            falseRegister();
                            return;
                        }
                    }
                }
                User user = new User(username, password);
                user.setFirstname(firstname);
                user.setInfix(infix);
                user.setLastname(lastname);
                user.setAddress(address);
                user.setAddressExtra(addressExtra);
                user.setCity(city);
                user.setCountry(country);
                user.setHouseNumber(houseNumber);
                user.setBirthday(birthday);
                users.add(user);
                FileUtil.add(FileUtil.USERS, users);

            }
        } catch (CharNotSupportedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void falseRegister() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
